### ISSUE TITLE
Update to new PyPy3 version.

### ISSUE THREAD

**Issue by sallner** [themattrix/docker-tox-base#2]
First, thanks for the base and the actual tox package. It enabled me to use my usual tox configuration directly with docker images. That's excellent work!

Now I have request and a question of understanding:
We are currently at a version 5.8.0  for PyPy3 which actually is compatible with CPython 3.5. It would be nice to have that included here. Unfortunately I do not understand where the `python-versions.txt` is somehow read or included in the build process. Is it just the change of the version number in this file?

**Comment by bittner** [comment]
Are you sure that you use version 3.**8**.0 of PyPy3? The [pyenv project](https://github.com/pyenv/pyenv/tree/master/plugins/python-build/share/python-build) lists "pypy3.5-6.0.0" and  "pypy-5.7.1" as the latest PyPy versions.

**Comment by themattrix** [comment]
This is now fixed by #6 and #7.

**Comment by bittner** [comment]
Thanks for merging! :+1: 

However, there seems to still be an issue with the image. The builds for `pypy3` are building with Python 3.7. See this build output, which I get on both GitLab CI and Codeship:

```bash
$ tox -e pypy3
pypy3 create: /builds/painless-software/painless-continuous-delivery/.tox/pypy3
ERROR: invocation failed (exit code 1), logfile: /builds/painless-software/painless-continuous-delivery/.tox/pypy3/log/pypy3-0.log
ERROR: actionid: pypy3
msg: getenv
cmdargs: ['/.pyenv/versions/3.7.0/bin/python', '-m', 'virtualenv', '--python', '/.pyenv/shims/pypy3', 'pypy3']

Using base prefix '/.pyenv/versions/pypy3.3-5.5-alpha'
New pypy executable in /builds/painless-software/painless-continuous-delivery/.tox/pypy3/bin/pypy3
Also creating executable in /builds/painless-software/painless-continuous-delivery/.tox/pypy3/bin/pypy
Installing setuptools, pip, wheel...
  Complete output from command /builds/painless-sof....tox/pypy3/bin/pypy3 - setuptools pip wheel:
  DEPRECATION: Python 3.3 supported has been deprecated and support for it will be dropped in the future. Please upgrade your Python.
Looking in links: /.pyenv/versions/3.7.0/lib/python3.7/site-packages, /.pyenv/versions/3.7.0/lib/python3.7/site-packages/virtualenv_support
Collecting setuptools
  Using cached https://files.pythonhosted.org/packages/7f/e1/820d941153923aac1d49d7fc37e17b6e73bfbd2904959fffbad77900cf92/setuptools-39.2.0-py2.py3-none-any.whl
Collecting pip
Collecting wheel
wheel requires Python '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*' but the running Python is 3.3.5
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/.pyenv/versions/3.7.0/lib/python3.7/site-packages/virtualenv.py", line 2343, in <module>
    main()
  File "/.pyenv/versions/3.7.0/lib/python3.7/site-packages/virtualenv.py", line 712, in main
    symlink=options.symlink)
  File "/.pyenv/versions/3.7.0/lib/python3.7/site-packages/virtualenv.py", line 947, in create_environment
    download=download,
  File "/.pyenv/versions/3.7.0/lib/python3.7/site-packages/virtualenv.py", line 904, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/.pyenv/versions/3.7.0/lib/python3.7/site-packages/virtualenv.py", line 796, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /builds/painless-sof....tox/pypy3/bin/pypy3 - setuptools pip wheel failed with error code 1
Running virtualenv with interpreter /.pyenv/shims/pypy3

ERROR: Error creating virtualenv. Note that some special characters (e.g. ':' and unicode symbols) in paths are not supported by virtualenv. Error details: InvocationError('/.pyenv/versions/3.7.0/bin/python -m virtualenv --python /.pyenv/shims/pypy3 pypy3 (see /builds/painless-software/painless-continuous-delivery/.tox/pypy3/log/pypy3-0.log)', 1)
___________________________________ summary ____________________________________
ERROR:   pypy3: Error creating virtualenv. Note that some special characters (e.g. ':' and unicode symbols) in paths are not supported by virtualenv. Error details: InvocationError('/.pyenv/versions/3.7.0/bin/python -m virtualenv --python /.pyenv/shims/pypy3 pypy3 (see /builds/painless-software/painless-continuous-delivery/.tox/pypy3/log/pypy3-0.log)', 1)
ERROR: Job failed: exit code 1
```
The builds are using the [painless/tox](https://hub.docker.com/r/painless/tox/builds/) image, which refers to `themattrix/tox-base` as a dependency. Is tracing this dependency not enough for rebuilding the image correctly? It should be, shouldn't it?

Or is Tox mistakenly interpreting the PyPy3 version for a CPython version, and _this_ makes the build fail? As of:

```bash
...
Installing setuptools, pip, wheel...
  Complete output from command /builds/painless-sof....tox/pypy3/bin/pypy3 - setuptools pip wheel:
  DEPRECATION: Python 3.3 supported has been deprecated and support for it will be dropped in the future. Please upgrade your Python.
Looking in links: /.pyenv/versions/3.7.0/lib/python3.7/site-packages, /.pyenv/versions/3.7.0/lib/python3.7/site-packages/virtualenv_support
...
```

**Comment by bittner** [comment]
This line makes me wonder:
```bash
Using base prefix '/.pyenv/versions/pypy3.3-5.5-alpha'
```
The updated image should be using `pypy3.5-6.0.0`. Not `pypy3.3-5.5-alpha`.

**Comment by bittner** [comment]
This is absolutely weird. I've removed all Docker images named "tox" from my machine, and then ran the commands below afresh. Here's what the output now is:

```bash
$ docker run --rm painless/tox:latest pyenv global
2.6.9
2.7.15
3.3.7
3.4.9
3.5.6
3.6.6
3.7.0
pypy3.3-5.5-alpha
pypy3.5-6.0.0
pypy-5.7.1
```
```bash
$ docker run --rm painless/tox:latest pypy3 --version
Python 3.3.5 (ea9979b550eeae87924dc4bef06070e8f8d0e22f, Oct 13 2016, 11:32:23)
[PyPy 5.5.0-alpha0 with GCC 6.2.0]
```
versus

```bash
$ docker run --rm themattrix/tox:latest pyenv global
2.6.9
2.7.13
3.3.6
3.4.5
3.5.2
3.6.0
pypy3.3-5.2-alpha1
pypy-5.4.1
```
```bash
$ docker run --rm themattrix/tox:latest pypy3 --version
Python 3.3.5 (27fa55f3a61023d76af3b38f34d1401b0b186076, May 31 2016, 17:54:15)
[PyPy 5.2.0-alpha0 with GCC 4.9.2]
```

1. Why does the _painless_ image have newer PyPy version than _themattrix_ one, when it's really just inheriting from it and installing Git?
1. Do we have to change the order in the `python-versions.txt` file to make `pypy3` be `pypy3.5` by default?

**Comment by bittner** [comment]
@themattrix Can you see this, too? Do you happen to know what the problem could be?

**Comment by themattrix** [comment]
Ah...so here's what was going on: The `tox` image was still using an outdated `tox-base` image. I've rebuilt `themattrix/tox` and it seems to be working now. Let me know if that fixes the issue on your end!

**Comment by themattrix** [comment]
Here's the current list:

```
$ docker run --rm themattrix/tox:latest pyenv global
2.6.9
2.7.15
3.3.7
3.4.9
3.5.6
3.6.6
3.7.0
pypy3.3-5.5-alpha
pypy3.5-6.0.0
pypy-5.7.1
```

The unfortunate part is that `pypy3` refers to `pypy3.3-5.5-alpha` and not `pypy3.5-6.0.0` (as you've pointed out). I'll see what I can do about that...

```
$ docker run --rm themattrix/tox:latest pypy3 --version
Python 3.3.5 (ea9979b550eeae87924dc4bef06070e8f8d0e22f, Oct 13 2016, 11:32:23)
[PyPy 5.5.0-alpha0 with GCC 6.2.0]
```

**Comment by themattrix** [comment]
I think I've figured it out. `pyenv` does its own lexical sorting of the installed versions. It stores this list in `/.pyenv/version`. This list is identical to `/python-versions.txt` but is simply in a different order. When I replace `/.pyenv/version` with `/python-versions.txt`, `pypy3` suddenly refers to `pypy3.5-6.0.0` and `python3` switches to `3.7.0`.

I will update `themattrix/pyenv` to perform this replacement, and I expect this to solve the ordering issue.

**Comment by themattrix** [comment]
Hooray! How does this look, @bittner?

```
$ docker run --rm themattrix/tox:latest pyenv global
3.7.0
3.6.6
3.5.6
3.4.9
3.3.7
2.7.15
2.6.9
pypy-5.7.1
pypy3.5-6.0.0
pypy3.3-5.5-alpha

$ docker run --rm themattrix/tox:latest pypy --version
Python 2.7.13 (1aa2d8e03cdfab54b7121e93fda7e98ea88a30bf, Apr 04 2017, 12:21:42)
[PyPy 5.7.1 with GCC 6.3.0]

$ docker run --rm themattrix/tox:latest pypy3 --version
Python 3.5.3 (fdd60ed87e94, Apr 24 2018, 06:10:04)
[PyPy 6.0.0 with GCC 6.2.0 20160901]

$ docker run --rm themattrix/tox:latest python3 --version
Python 3.7.0

$ docker run --rm themattrix/tox:latest python2 --version
Python 2.7.15
```

**Comment by bittner** [comment]
Thanks for your effort and attention to detail! :+1:

One last thing: While totally unnecessary and only of esthetic make, you *could* put `pypy` at the end of the list.

This way we would have all the Python versions (visually) ordered from the latest to the oldest version.

As I said, optional.
